language: node_js
node_js:
- '6.10'
cache:
  directories:
    - node_modules

script:
    - npm install
    - npm run test:e2e:deploy
    - npm test

after_script: nyc report --reporter=text-lcov | coveralls
